// Pure generation for `asterism service` — the deploy target that keeps one
// agent's long-lived command (`serve` or a chat channel) running under the
// operating system's own service manager: a launchd user agent on macOS, a
// systemd user unit on Linux.
//
// Everything here is a PURE function of its inputs — no filesystem, no process,
// no clock — so the unit/plist/wrapper text is fully unit-testable. The command
// handler in `cli.ts` owns the side effects (writing files, calling
// `launchctl`/`systemctl`); this module only renders.
//
// Design notes that shape what we emit:
//   - One service supervises ONE long-lived command for ONE agent. The agent
//     boundary is preserved exactly as on the command line.
//   - The service runs with a minimal environment (launchd and systemd do not
//     inherit your interactive shell), so every path baked in is ABSOLUTE and the
//     command is launched through a small wrapper that sources a private env file.
//   - Secrets are NEVER written here. The wrapper sources an env file the operator
//     fills in; this module only ever names the variables a service needs.

/** The long-lived commands a service can supervise. */
export type ServiceKind = "serve" | "telegram" | "discord";

/** Every supported service kind, in display order. */
export const SERVICE_KINDS: readonly ServiceKind[] = ["serve", "telegram", "discord"];

/** Narrow an arbitrary string to a {@link ServiceKind}. */
export function isServiceKind(value: string): value is ServiceKind {
  return (SERVICE_KINDS as readonly string[]).includes(value);
}

/** The `asterism` sub-command (without the binary) a service of this kind runs. */
export function serviceCommand(kind: ServiceKind, agentName: string): string[] {
  switch (kind) {
    case "serve":
      return ["serve", agentName];
    case "telegram":
      return ["channel", "telegram", agentName];
    case "discord":
      return ["channel", "discord", agentName];
  }
}

/** Reverse-DNS launchd label for an agent's service of a given kind (macOS). */
export function launchdLabel(agentName: string, kind: ServiceKind): string {
  return `com.qmilab.asterism.${agentName}.${kind}`;
}

/** systemd user-unit file name for an agent's service of a given kind (Linux). */
export function systemdUnitName(agentName: string, kind: ServiceKind): string {
  return `asterism-${agentName}-${kind}.service`;
}

/**
 * Single-quote a token for safe inclusion in a POSIX `sh` command line. Wrapping
 * in single quotes disables every shell metacharacter; an embedded single quote is
 * closed, escaped, and reopened (`'\''`). Load-bearing: the service argv can carry
 * operator-supplied passthrough arguments, and an absolute path may contain spaces.
 */
export function shQuote(token: string): string {
  return `'${token.replace(/'/g, `'\\''`)}'`;
}

/** Escape a string for inclusion in an XML text node / attribute (launchd plist). */
function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export interface WrapperSpec {
  /** The label/name this wrapper belongs to — used only in the header comment. */
  label: string;
  /** Absolute argv to exec, e.g. `[node, bin.js, "serve", "writer", "--port", "8080"]`. */
  argv: readonly string[];
  /** The directory the command runs in — the directory that contains `.asterism`. */
  workingDir: string;
  /** Absolute path to the private env file the wrapper sources (may not exist yet). */
  envFile: string;
}

/**
 * Render the small `sh` wrapper both service managers invoke. It sources the
 * service's private env file if present (so the operator's secrets reach the run
 * without ever being written into a unit file), changes into the install
 * directory, and execs the absolute command. Used identically on both platforms
 * so there is a single env-sourcing code path.
 */
export function renderWrapper(spec: WrapperSpec): string {
  const command = spec.argv.map(shQuote).join(" ");
  return [
    "#!/bin/sh",
    `# Generated by 'asterism service install' for ${spec.label}.`,
    "# Keeps one agent's long-lived command running under your OS service manager.",
    "# Secrets (model API key, chat-bot token) are read from the env file below —",
    "# fill that in yourself. Do not commit it, and do not edit this wrapper by hand;",
    "# 'asterism service install' regenerates it.",
    "set -a",
    `[ -r ${shQuote(spec.envFile)} ] && . ${shQuote(spec.envFile)}`,
    "set +a",
    `cd ${shQuote(spec.workingDir)} || exit 1`,
    `exec ${command}`,
    "",
  ].join("\n");
}

export interface LaunchdSpec {
  label: string;
  /** Absolute path to the wrapper script the agent runs. */
  wrapperPath: string;
  /** The directory the command runs in (contains `.asterism`). */
  workingDir: string;
  /** Absolute path the service's combined stdout/stderr is written to. */
  logFile: string;
}

/**
 * Render a launchd user-agent property list. `RunAtLoad` starts it at login;
 * `KeepAlive`/`SuccessfulExit:false` restarts it only when it crashes or exits
 * non-zero (so a clean `stop` stays stopped); `ThrottleInterval` backs off a
 * service that keeps failing (e.g. one whose env file is not filled in yet)
 * instead of hot-looping.
 */
export function renderLaunchdPlist(spec: LaunchdSpec): string {
  const x = xmlEscape;
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`,
    `<plist version="1.0">`,
    `<dict>`,
    `  <key>Label</key>`,
    `  <string>${x(spec.label)}</string>`,
    `  <key>ProgramArguments</key>`,
    `  <array>`,
    `    <string>/bin/sh</string>`,
    `    <string>${x(spec.wrapperPath)}</string>`,
    `  </array>`,
    `  <key>WorkingDirectory</key>`,
    `  <string>${x(spec.workingDir)}</string>`,
    `  <key>RunAtLoad</key>`,
    `  <true/>`,
    `  <key>KeepAlive</key>`,
    `  <dict>`,
    `    <key>SuccessfulExit</key>`,
    `    <false/>`,
    `  </dict>`,
    `  <key>ThrottleInterval</key>`,
    `  <integer>10</integer>`,
    `  <key>ProcessType</key>`,
    `  <string>Background</string>`,
    `  <key>StandardOutPath</key>`,
    `  <string>${x(spec.logFile)}</string>`,
    `  <key>StandardErrorPath</key>`,
    `  <string>${x(spec.logFile)}</string>`,
    `</dict>`,
    `</plist>`,
    "",
  ].join("\n");
}

export interface SystemdSpec {
  description: string;
  /** Absolute path to the wrapper script the unit runs. */
  wrapperPath: string;
  /** The directory the command runs in (contains `.asterism`). */
  workingDir: string;
}

/** Escape a literal `%` so systemd does not read it as a specifier in a unit value. */
function systemdLiteral(value: string): string {
  return value.replace(/%/g, "%%");
}

/**
 * Quote a path as a single systemd command argument. systemd splits `ExecStart` on
 * unquoted whitespace and treats `%` as a specifier, so a generated path with a
 * space (a home directory with a space) or a `%` would otherwise be mis-parsed.
 * Wrap in double quotes, escape `\` and `"`, and double `%`.
 */
function systemdArg(value: string): string {
  const escaped = systemdLiteral(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"${escaped}"`;
}

/**
 * Render a systemd user-unit file. `Restart=on-failure` with a `RestartSec` back-off
 * restarts a crashed service without hot-looping a misconfigured one;
 * `WantedBy=default.target` starts it on login (boot start additionally needs
 * lingering — surfaced in the install output, not forced here).
 */
export function renderSystemdUnit(spec: SystemdSpec): string {
  return [
    "[Unit]",
    `Description=${systemdLiteral(spec.description)}`,
    "After=network-online.target",
    "Wants=network-online.target",
    "",
    "[Service]",
    "Type=simple",
    `WorkingDirectory=${systemdArg(spec.workingDir)}`,
    `ExecStart=/bin/sh ${systemdArg(spec.wrapperPath)}`,
    "Restart=on-failure",
    "RestartSec=5",
    "",
    "[Install]",
    "WantedBy=default.target",
    "",
  ].join("\n");
}

/** One environment variable a service needs, for the env-file template. */
export interface EnvVarSpec {
  name: string;
  required: boolean;
  /** A short human note on what the variable is for. */
  note: string;
}

/**
 * Render the private env-file template the wrapper sources. Every variable is
 * emitted COMMENTED OUT with no value — this file names what a service needs; the
 * operator fills in the secrets. We never write a secret value here.
 */
export function renderEnvTemplate(label: string, vars: readonly EnvVarSpec[]): string {
  const lines = [
    `# Environment for ${label}.`,
    "# Fill in the values this service needs, then keep this file private.",
    "# 'asterism service install' created it with 0600 permissions and will not",
    "# overwrite it once you have edited it. Each line is KEY=value; wrap a value in",
    "# single quotes if it contains spaces or special characters.",
    "",
  ];
  for (const v of vars) {
    lines.push(`# ${v.required ? "Required" : "Optional"} — ${v.note}`);
    lines.push(`# ${v.name}=`);
    lines.push("");
  }
  return lines.join("\n");
}

/**
 * Render the env file with values CAPTURED from the operator's environment — only
 * for `service install --capture-env`, an explicit opt-in to write secret values
 * to disk. A variable present in the environment is emitted as a real assignment,
 * shell-quoted (the wrapper sources this file with `.`, so a value with spaces or
 * special characters must be quoted to survive); a variable that is absent stays a
 * commented placeholder, exactly as in the template.
 */
export function renderEnvFile(
  label: string,
  vars: readonly EnvVarSpec[],
  lookup: (name: string) => string | undefined,
): string {
  const lines = [
    `# Environment for ${label}.`,
    "# Captured from your environment by 'asterism service install --capture-env'.",
    "# It holds secrets — keep it private (created with 0600 permissions). Re-running",
    "# with --capture-env overwrites it; without the flag it is left untouched.",
    "",
  ];
  for (const v of vars) {
    const value = lookup(v.name);
    lines.push(`# ${v.required ? "Required" : "Optional"} — ${v.note}`);
    lines.push(value !== undefined ? `${v.name}=${shQuote(value)}` : `# ${v.name}=`);
    lines.push("");
  }
  return lines.join("\n");
}
